
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelnetMVC.Entities
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// 科室字典
    /// </summary>
    [Serializable]
    public partial class DeptDict
    {
        public string Id { get; set; }
        public string DeptName { get; set; }
        public string OrgCode { get; set; }
        public string UpDeptId { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Modify { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    }
}
